baseurl = "/"
languageCode = "en"
disableRSS = true
MetaDataFormat = "toml"
[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Portfolio"
  weight = 2
  identifier = "portfolio"
  url = "/portfolio/"
[[menu.main]]
  name = "About Us"
  weight = 3
  identifier = "about-us"
  url = "/about-us/"
